name: '{ACCOUNT_NAME}: Terraform Continuous Integration And Deployment'

on:
  push:
    branches:
     - 'main'
    paths:
    - 'terraform/{ACCOUNT_PROFILE}/**'
  pull_request:
    branches:
     - 'main'
    paths:
    - 'terraform/{ACCOUNT_PROFILE}/**'

jobs:
  terraform:
    name: 'Terraform {ACCOUNT_NAME}'
    runs-on: ubuntu-latest
    environment: {ENVIRONMENT}

    # Use the Bash shell
    defaults:
      run:
        shell: bash
        working-directory: terraform/{ACCOUNT_PROFILE}/

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Add AWS profile and Git key settings
      env:
        AWS_ACCESS_KEY: ${{ secrets.AWS_{GHA}_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_{GHA}_SECRET_KEY }}

      run: |
        aws configure set aws_access_key_id $AWS_ACCESS_KEY --profile {ACCOUNT_PROFILE}
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY --profile {ACCOUNT_PROFILE}
        git config --global url."https://oauth2:${{ secrets.GHA_RUNNER_TOKEN }}@github.com".insteadOf https://github.com

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: 'Terraform Init'
      id: init
      run: terraform init

    - name: Terraform Format
      id: fmt
      run: terraform fmt -check

    - name: Terraform Plan
      id: plan
      if: github.event_name == 'pull_request'
      run: terraform plan -no-color
